export const EMPTY_SHELF = 'EMPTY_SHELF';
export const SIGN_UP_VERIFY_EMAIL = 'SIGN_UP_VERIFY_EMAIL';
export const SIGN_IN_EMAIL_NOT_VERIFIED = 'SIGN_UP_EMAIL_NOT_VERIFIED';
export const ADD_REVIEW_COMMENT_UNLOGGED = 'ADD_REVIEW_COMMENT_UNLOGGED';
export const ADD_REVIEW_REPEATED = 'ADD_REVIEW_REPEATED';