export const ADD_PRODUCT_TO_BOOKSHELF = 'ADD_PRODUCT_TO_BOOKSHELF';
export const REMOVE_SOME_FROM_BOOKSHELF = 'REMOVE_SOME_FROM_BOOKSHELF';
export const REMOVE_ALL_FROM_BOOKSHELF = 'REMOVE_ALL_FROM_BOOKSHELF';


export const CHANGE_LIST_PAGE = 'CHANGE_LIST_PAGE';