export const ADD_PRODUCT_TO_BOOKSHELF = 'ADD_PRODUCT_TO_BOOKSHELF';
export const REMOVE_SOME_FROM_BOOKSHELF = 'REMOVE_SOME_FROM_BOOKSHELF';
export const REMOVE_ALL_FROM_BOOKSHELF = 'REMOVE_ALL_FROM_BOOKSHELF';

export const CHANGE_LIST_PAGE = 'CHANGE_LIST_PAGE';

export const CHANGE_CHECK = 'CHANGE_CHECK';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';

export const CHANGE_OPENED_DIALOG = 'CHANGE_OPENED_DIALOG';

export const SET_LOADING = 'SET_LOADING';